# Generated by Django 4.0.4 on 2022-11-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_stat', 'Can read all the farms')]},
        ),
    ]
